version: '3.8'

services:
  db:
    image: postgres:15-alpine
    container_name: my_pgdb
    environment:
      POSTGRES_USER: demo
      POSTGRES_PASSWORD: demo
      POSTGRES_DB: testdb
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U demo -d testdb"]
      interval: 5s
      timeout: 5s
      retries: 5

  fastapi-service:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: fastapi_app
    environment:
      DB_HOST: db
      DB_PORT: 5433
      DB_USER: demo
      DB_PASSWORD: demo
      DB_NAME: testdb
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy
    command: >
      bash -c "alembic upgrade head && 
               python -m uvicorn app.main:app --host 0.0.0.0 --port 8000"

volumes:
  db_data:
