apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-config
  namespace: postgres-ns
data:
  POSTGRES_USER: "postgres"
  postgresql.conf: |
    listen_addresses = '*'
    hba_file = '/etc/postgresql/pg_hba.conf'
    max_connections = 100
    shared_buffers = 128MB
    log_destination = 'stderr'
    logging_collector = off

  pg_hba.conf: |
    local   all             all                                     trust
    host    all             all             0.0.0.0/0               md5
    host    all             all             ::/0                    md5
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgres
  namespace: postgres-ns
spec:
  serviceName: postgres
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
                - key: type
                  operator: In
                  values:
                    - database
      containers:
        - name: postgres
          image: postgres:latest
          ports:
            - containerPort: 5432
          args:
            - "-c"
            - "config_file=/etc/postgresql/postgresql.conf"
          env:
            - name: POSTGRES_USER
              valueFrom:
                configMapKeyRef:
                  name: postgres-config
                  key: POSTGRES_USER
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: POSTGRES_PASSWORD
          volumeMounts:
            - name: postgres-storage
              mountPath: /var/lib/postgresql/data
            - name: postgres-config
              mountPath: /etc/postgresql/postgresql.conf
              subPath: postgresql.conf
            - name: postgres-config
              mountPath: /etc/postgresql/pg_hba.conf
              subPath: pg_hba.conf
      volumes:
        - name: postgres-config
          configMap:
            name: postgres-config
  volumeClaimTemplates:
    - metadata:
        name: postgres-storage
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 1Gi
---
apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: postgres-ns
type: Opaque
data:
  POSTGRES_PASSWORD: "cG9zdGdyZXM="  # Base64 of 'postgres'
---
apiVersion: v1
kind: Service
metadata:
  name: postgres-service
  namespace: postgres-ns
spec:
  selector:
    app: postgres
  ports:
    - port: 5432
      targetPort: 5432
      nodePort: 30080
  type: LoadBalancer
