server:
  dataStorage:
    enabled: true
    size: 1Gi
    storageClass: standard
  securityContext:
    runAsUser: 100
    runAsGroup: 1000
    fsGroup: 1000
    runAsNonRoot: true
  extraInitContainers:
    - name: fix-permissions
      image: busybox
      command:
        - sh
        - -c
        - chown -R 100:1000 /vault/data
      securityContext:
        runAsUser: 0
        runAsGroup: 0
        runAsNonRoot: false  # <-- IMPORTANT!
      volumeMounts:
        - name: data
          mountPath: /vault/data
